apiVersion: v1
kind: Secret
metadata:
  name: mapreduce-secrets
  namespace: mapreduce
type: Opaque
stringData:
  # PostgreSQL
  POSTGRES_USER:     "mapreduce"
  POSTGRES_PASSWORD: "mapreduce_dev"
  POSTGRES_DB:       "mapreduce"
  POSTGRES_DSN:          "postgres://mapreduce:mapreduce_dev@postgres-primary.mapreduce.svc.cluster.local:5432/mapreduce?sslmode=disable"
  POSTGRES_DSN_READONLY: "postgres://mapreduce:mapreduce_dev@postgres-replica.mapreduce.svc.cluster.local:5432/mapreduce?sslmode=disable"
  REPLICATOR_PASSWORD: "replicator_dev"

  # MinIO
  MINIO_ROOT_USER:     "minioadmin"
  MINIO_ROOT_PASSWORD: "minioadmin_dev"
  MINIO_ACCESS_KEY: "minioadmin"
  MINIO_SECRET_KEY: "minioadmin_dev"

  # Keycloak
  KC_BOOTSTRAP_ADMIN_USERNAME: "kcadmin"
  KC_BOOTSTRAP_ADMIN_PASSWORD: "kcadmin_dev_only"
  KEYCLOAK_ADMIN_USER:     "kcadmin"
  KEYCLOAK_ADMIN_PASSWORD: "kcadmin_dev_only"
  KEYCLOAK_POSTGRES_DSN: "jdbc:postgresql://postgres-primary.mapreduce.svc.cluster.local:5432/mapreduce?sslmode=disable&user=mapreduce&password=mapreduce_dev"