// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package db

import (
	"context"
	"database/sql"
	"fmt"
)

type DBTX interface {
	ExecContext(context.Context, string, ...interface{}) (sql.Result, error)
	PrepareContext(context.Context, string) (*sql.Stmt, error)
	QueryContext(context.Context, string, ...interface{}) (*sql.Rows, error)
	QueryRowContext(context.Context, string, ...interface{}) *sql.Row
}

func New(db DBTX) *Queries {
	return &Queries{db: db}
}

func Prepare(ctx context.Context, db DBTX) (*Queries, error) {
	q := Queries{db: db}
	var err error
	if q.cancelJobStmt, err = db.PrepareContext(ctx, cancelJob); err != nil {
		return nil, fmt.Errorf("error preparing query CancelJob: %w", err)
	}
	if q.countJobsByStatusStmt, err = db.PrepareContext(ctx, countJobsByStatus); err != nil {
		return nil, fmt.Errorf("error preparing query CountJobsByStatus: %w", err)
	}
	if q.countMapTasksByStatusStmt, err = db.PrepareContext(ctx, countMapTasksByStatus); err != nil {
		return nil, fmt.Errorf("error preparing query CountMapTasksByStatus: %w", err)
	}
	if q.countReduceTasksByStatusStmt, err = db.PrepareContext(ctx, countReduceTasksByStatus); err != nil {
		return nil, fmt.Errorf("error preparing query CountReduceTasksByStatus: %w", err)
	}
	if q.createJobStmt, err = db.PrepareContext(ctx, createJob); err != nil {
		return nil, fmt.Errorf("error preparing query CreateJob: %w", err)
	}
	if q.createMapTaskStmt, err = db.PrepareContext(ctx, createMapTask); err != nil {
		return nil, fmt.Errorf("error preparing query CreateMapTask: %w", err)
	}
	if q.createReduceTaskStmt, err = db.PrepareContext(ctx, createReduceTask); err != nil {
		return nil, fmt.Errorf("error preparing query CreateReduceTask: %w", err)
	}
	if q.failJobStmt, err = db.PrepareContext(ctx, failJob); err != nil {
		return nil, fmt.Errorf("error preparing query FailJob: %w", err)
	}
	if q.getActiveJobsByReplicaStmt, err = db.PrepareContext(ctx, getActiveJobsByReplica); err != nil {
		return nil, fmt.Errorf("error preparing query GetActiveJobsByReplica: %w", err)
	}
	if q.getAllJobsStmt, err = db.PrepareContext(ctx, getAllJobs); err != nil {
		return nil, fmt.Errorf("error preparing query GetAllJobs: %w", err)
	}
	if q.getJobStmt, err = db.PrepareContext(ctx, getJob); err != nil {
		return nil, fmt.Errorf("error preparing query GetJob: %w", err)
	}
	if q.getJobsByUserStmt, err = db.PrepareContext(ctx, getJobsByUser); err != nil {
		return nil, fmt.Errorf("error preparing query GetJobsByUser: %w", err)
	}
	if q.getMapTaskStmt, err = db.PrepareContext(ctx, getMapTask); err != nil {
		return nil, fmt.Errorf("error preparing query GetMapTask: %w", err)
	}
	if q.getMapTaskOutputLocationsStmt, err = db.PrepareContext(ctx, getMapTaskOutputLocations); err != nil {
		return nil, fmt.Errorf("error preparing query GetMapTaskOutputLocations: %w", err)
	}
	if q.getMapTasksByJobStmt, err = db.PrepareContext(ctx, getMapTasksByJob); err != nil {
		return nil, fmt.Errorf("error preparing query GetMapTasksByJob: %w", err)
	}
	if q.getMapTasksByJobAndStatusStmt, err = db.PrepareContext(ctx, getMapTasksByJobAndStatus); err != nil {
		return nil, fmt.Errorf("error preparing query GetMapTasksByJobAndStatus: %w", err)
	}
	if q.getPendingMapTasksStmt, err = db.PrepareContext(ctx, getPendingMapTasks); err != nil {
		return nil, fmt.Errorf("error preparing query GetPendingMapTasks: %w", err)
	}
	if q.getPendingReduceTasksStmt, err = db.PrepareContext(ctx, getPendingReduceTasks); err != nil {
		return nil, fmt.Errorf("error preparing query GetPendingReduceTasks: %w", err)
	}
	if q.getReduceTaskStmt, err = db.PrepareContext(ctx, getReduceTask); err != nil {
		return nil, fmt.Errorf("error preparing query GetReduceTask: %w", err)
	}
	if q.getReduceTaskOutputPathsStmt, err = db.PrepareContext(ctx, getReduceTaskOutputPaths); err != nil {
		return nil, fmt.Errorf("error preparing query GetReduceTaskOutputPaths: %w", err)
	}
	if q.getReduceTasksByJobStmt, err = db.PrepareContext(ctx, getReduceTasksByJob); err != nil {
		return nil, fmt.Errorf("error preparing query GetReduceTasksByJob: %w", err)
	}
	if q.getReduceTasksByJobAndStatusStmt, err = db.PrepareContext(ctx, getReduceTasksByJobAndStatus); err != nil {
		return nil, fmt.Errorf("error preparing query GetReduceTasksByJobAndStatus: %w", err)
	}
	if q.getStaleRunningMapTasksStmt, err = db.PrepareContext(ctx, getStaleRunningMapTasks); err != nil {
		return nil, fmt.Errorf("error preparing query GetStaleRunningMapTasks: %w", err)
	}
	if q.getStaleRunningReduceTasksStmt, err = db.PrepareContext(ctx, getStaleRunningReduceTasks); err != nil {
		return nil, fmt.Errorf("error preparing query GetStaleRunningReduceTasks: %w", err)
	}
	if q.incrementMapTaskRetryStmt, err = db.PrepareContext(ctx, incrementMapTaskRetry); err != nil {
		return nil, fmt.Errorf("error preparing query IncrementMapTaskRetry: %w", err)
	}
	if q.incrementReduceTaskRetryStmt, err = db.PrepareContext(ctx, incrementReduceTaskRetry); err != nil {
		return nil, fmt.Errorf("error preparing query IncrementReduceTaskRetry: %w", err)
	}
	if q.markMapTaskCompletedStmt, err = db.PrepareContext(ctx, markMapTaskCompleted); err != nil {
		return nil, fmt.Errorf("error preparing query MarkMapTaskCompleted: %w", err)
	}
	if q.markMapTaskFailedStmt, err = db.PrepareContext(ctx, markMapTaskFailed); err != nil {
		return nil, fmt.Errorf("error preparing query MarkMapTaskFailed: %w", err)
	}
	if q.markMapTaskRunningStmt, err = db.PrepareContext(ctx, markMapTaskRunning); err != nil {
		return nil, fmt.Errorf("error preparing query MarkMapTaskRunning: %w", err)
	}
	if q.markReduceTaskCompletedStmt, err = db.PrepareContext(ctx, markReduceTaskCompleted); err != nil {
		return nil, fmt.Errorf("error preparing query MarkReduceTaskCompleted: %w", err)
	}
	if q.markReduceTaskFailedStmt, err = db.PrepareContext(ctx, markReduceTaskFailed); err != nil {
		return nil, fmt.Errorf("error preparing query MarkReduceTaskFailed: %w", err)
	}
	if q.markReduceTaskRunningStmt, err = db.PrepareContext(ctx, markReduceTaskRunning); err != nil {
		return nil, fmt.Errorf("error preparing query MarkReduceTaskRunning: %w", err)
	}
	if q.updateJobStatusStmt, err = db.PrepareContext(ctx, updateJobStatus); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateJobStatus: %w", err)
	}
	return &q, nil
}

func (q *Queries) Close() error {
	var err error
	if q.cancelJobStmt != nil {
		if cerr := q.cancelJobStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing cancelJobStmt: %w", cerr)
		}
	}
	if q.countJobsByStatusStmt != nil {
		if cerr := q.countJobsByStatusStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing countJobsByStatusStmt: %w", cerr)
		}
	}
	if q.countMapTasksByStatusStmt != nil {
		if cerr := q.countMapTasksByStatusStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing countMapTasksByStatusStmt: %w", cerr)
		}
	}
	if q.countReduceTasksByStatusStmt != nil {
		if cerr := q.countReduceTasksByStatusStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing countReduceTasksByStatusStmt: %w", cerr)
		}
	}
	if q.createJobStmt != nil {
		if cerr := q.createJobStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createJobStmt: %w", cerr)
		}
	}
	if q.createMapTaskStmt != nil {
		if cerr := q.createMapTaskStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createMapTaskStmt: %w", cerr)
		}
	}
	if q.createReduceTaskStmt != nil {
		if cerr := q.createReduceTaskStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createReduceTaskStmt: %w", cerr)
		}
	}
	if q.failJobStmt != nil {
		if cerr := q.failJobStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing failJobStmt: %w", cerr)
		}
	}
	if q.getActiveJobsByReplicaStmt != nil {
		if cerr := q.getActiveJobsByReplicaStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getActiveJobsByReplicaStmt: %w", cerr)
		}
	}
	if q.getAllJobsStmt != nil {
		if cerr := q.getAllJobsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getAllJobsStmt: %w", cerr)
		}
	}
	if q.getJobStmt != nil {
		if cerr := q.getJobStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getJobStmt: %w", cerr)
		}
	}
	if q.getJobsByUserStmt != nil {
		if cerr := q.getJobsByUserStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getJobsByUserStmt: %w", cerr)
		}
	}
	if q.getMapTaskStmt != nil {
		if cerr := q.getMapTaskStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getMapTaskStmt: %w", cerr)
		}
	}
	if q.getMapTaskOutputLocationsStmt != nil {
		if cerr := q.getMapTaskOutputLocationsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getMapTaskOutputLocationsStmt: %w", cerr)
		}
	}
	if q.getMapTasksByJobStmt != nil {
		if cerr := q.getMapTasksByJobStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getMapTasksByJobStmt: %w", cerr)
		}
	}
	if q.getMapTasksByJobAndStatusStmt != nil {
		if cerr := q.getMapTasksByJobAndStatusStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getMapTasksByJobAndStatusStmt: %w", cerr)
		}
	}
	if q.getPendingMapTasksStmt != nil {
		if cerr := q.getPendingMapTasksStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getPendingMapTasksStmt: %w", cerr)
		}
	}
	if q.getPendingReduceTasksStmt != nil {
		if cerr := q.getPendingReduceTasksStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getPendingReduceTasksStmt: %w", cerr)
		}
	}
	if q.getReduceTaskStmt != nil {
		if cerr := q.getReduceTaskStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getReduceTaskStmt: %w", cerr)
		}
	}
	if q.getReduceTaskOutputPathsStmt != nil {
		if cerr := q.getReduceTaskOutputPathsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getReduceTaskOutputPathsStmt: %w", cerr)
		}
	}
	if q.getReduceTasksByJobStmt != nil {
		if cerr := q.getReduceTasksByJobStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getReduceTasksByJobStmt: %w", cerr)
		}
	}
	if q.getReduceTasksByJobAndStatusStmt != nil {
		if cerr := q.getReduceTasksByJobAndStatusStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getReduceTasksByJobAndStatusStmt: %w", cerr)
		}
	}
	if q.getStaleRunningMapTasksStmt != nil {
		if cerr := q.getStaleRunningMapTasksStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getStaleRunningMapTasksStmt: %w", cerr)
		}
	}
	if q.getStaleRunningReduceTasksStmt != nil {
		if cerr := q.getStaleRunningReduceTasksStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getStaleRunningReduceTasksStmt: %w", cerr)
		}
	}
	if q.incrementMapTaskRetryStmt != nil {
		if cerr := q.incrementMapTaskRetryStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing incrementMapTaskRetryStmt: %w", cerr)
		}
	}
	if q.incrementReduceTaskRetryStmt != nil {
		if cerr := q.incrementReduceTaskRetryStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing incrementReduceTaskRetryStmt: %w", cerr)
		}
	}
	if q.markMapTaskCompletedStmt != nil {
		if cerr := q.markMapTaskCompletedStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing markMapTaskCompletedStmt: %w", cerr)
		}
	}
	if q.markMapTaskFailedStmt != nil {
		if cerr := q.markMapTaskFailedStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing markMapTaskFailedStmt: %w", cerr)
		}
	}
	if q.markMapTaskRunningStmt != nil {
		if cerr := q.markMapTaskRunningStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing markMapTaskRunningStmt: %w", cerr)
		}
	}
	if q.markReduceTaskCompletedStmt != nil {
		if cerr := q.markReduceTaskCompletedStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing markReduceTaskCompletedStmt: %w", cerr)
		}
	}
	if q.markReduceTaskFailedStmt != nil {
		if cerr := q.markReduceTaskFailedStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing markReduceTaskFailedStmt: %w", cerr)
		}
	}
	if q.markReduceTaskRunningStmt != nil {
		if cerr := q.markReduceTaskRunningStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing markReduceTaskRunningStmt: %w", cerr)
		}
	}
	if q.updateJobStatusStmt != nil {
		if cerr := q.updateJobStatusStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateJobStatusStmt: %w", cerr)
		}
	}
	return err
}

func (q *Queries) exec(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (sql.Result, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).ExecContext(ctx, args...)
	case stmt != nil:
		return stmt.ExecContext(ctx, args...)
	default:
		return q.db.ExecContext(ctx, query, args...)
	}
}

func (q *Queries) query(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (*sql.Rows, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryContext(ctx, args...)
	default:
		return q.db.QueryContext(ctx, query, args...)
	}
}

func (q *Queries) queryRow(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) *sql.Row {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryRowContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryRowContext(ctx, args...)
	default:
		return q.db.QueryRowContext(ctx, query, args...)
	}
}

type Queries struct {
	db                               DBTX
	tx                               *sql.Tx
	cancelJobStmt                    *sql.Stmt
	countJobsByStatusStmt            *sql.Stmt
	countMapTasksByStatusStmt        *sql.Stmt
	countReduceTasksByStatusStmt     *sql.Stmt
	createJobStmt                    *sql.Stmt
	createMapTaskStmt                *sql.Stmt
	createReduceTaskStmt             *sql.Stmt
	failJobStmt                      *sql.Stmt
	getActiveJobsByReplicaStmt       *sql.Stmt
	getAllJobsStmt                   *sql.Stmt
	getJobStmt                       *sql.Stmt
	getJobsByUserStmt                *sql.Stmt
	getMapTaskStmt                   *sql.Stmt
	getMapTaskOutputLocationsStmt    *sql.Stmt
	getMapTasksByJobStmt             *sql.Stmt
	getMapTasksByJobAndStatusStmt    *sql.Stmt
	getPendingMapTasksStmt           *sql.Stmt
	getPendingReduceTasksStmt        *sql.Stmt
	getReduceTaskStmt                *sql.Stmt
	getReduceTaskOutputPathsStmt     *sql.Stmt
	getReduceTasksByJobStmt          *sql.Stmt
	getReduceTasksByJobAndStatusStmt *sql.Stmt
	getStaleRunningMapTasksStmt      *sql.Stmt
	getStaleRunningReduceTasksStmt   *sql.Stmt
	incrementMapTaskRetryStmt        *sql.Stmt
	incrementReduceTaskRetryStmt     *sql.Stmt
	markMapTaskCompletedStmt         *sql.Stmt
	markMapTaskFailedStmt            *sql.Stmt
	markMapTaskRunningStmt           *sql.Stmt
	markReduceTaskCompletedStmt      *sql.Stmt
	markReduceTaskFailedStmt         *sql.Stmt
	markReduceTaskRunningStmt        *sql.Stmt
	updateJobStatusStmt              *sql.Stmt
}

func (q *Queries) WithTx(tx *sql.Tx) *Queries {
	return &Queries{
		db:                               tx,
		tx:                               tx,
		cancelJobStmt:                    q.cancelJobStmt,
		countJobsByStatusStmt:            q.countJobsByStatusStmt,
		countMapTasksByStatusStmt:        q.countMapTasksByStatusStmt,
		countReduceTasksByStatusStmt:     q.countReduceTasksByStatusStmt,
		createJobStmt:                    q.createJobStmt,
		createMapTaskStmt:                q.createMapTaskStmt,
		createReduceTaskStmt:             q.createReduceTaskStmt,
		failJobStmt:                      q.failJobStmt,
		getActiveJobsByReplicaStmt:       q.getActiveJobsByReplicaStmt,
		getAllJobsStmt:                   q.getAllJobsStmt,
		getJobStmt:                       q.getJobStmt,
		getJobsByUserStmt:                q.getJobsByUserStmt,
		getMapTaskStmt:                   q.getMapTaskStmt,
		getMapTaskOutputLocationsStmt:    q.getMapTaskOutputLocationsStmt,
		getMapTasksByJobStmt:             q.getMapTasksByJobStmt,
		getMapTasksByJobAndStatusStmt:    q.getMapTasksByJobAndStatusStmt,
		getPendingMapTasksStmt:           q.getPendingMapTasksStmt,
		getPendingReduceTasksStmt:        q.getPendingReduceTasksStmt,
		getReduceTaskStmt:                q.getReduceTaskStmt,
		getReduceTaskOutputPathsStmt:     q.getReduceTaskOutputPathsStmt,
		getReduceTasksByJobStmt:          q.getReduceTasksByJobStmt,
		getReduceTasksByJobAndStatusStmt: q.getReduceTasksByJobAndStatusStmt,
		getStaleRunningMapTasksStmt:      q.getStaleRunningMapTasksStmt,
		getStaleRunningReduceTasksStmt:   q.getStaleRunningReduceTasksStmt,
		incrementMapTaskRetryStmt:        q.incrementMapTaskRetryStmt,
		incrementReduceTaskRetryStmt:     q.incrementReduceTaskRetryStmt,
		markMapTaskCompletedStmt:         q.markMapTaskCompletedStmt,
		markMapTaskFailedStmt:            q.markMapTaskFailedStmt,
		markMapTaskRunningStmt:           q.markMapTaskRunningStmt,
		markReduceTaskCompletedStmt:      q.markReduceTaskCompletedStmt,
		markReduceTaskFailedStmt:         q.markReduceTaskFailedStmt,
		markReduceTaskRunningStmt:        q.markReduceTaskRunningStmt,
		updateJobStatusStmt:              q.updateJobStatusStmt,
	}
}
