// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: jobs.sql

package db

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const cancelJob = `-- name: CancelJob :exec
UPDATE jobs
SET
    status       = 'CANCELLED',
    completed_at = NOW()
WHERE job_id = $1
  AND status NOT IN ('COMPLETED', 'FAILED', 'CANCELLED')
`

func (q *Queries) CancelJob(ctx context.Context, jobID uuid.UUID) error {
	_, err := q.exec(ctx, q.cancelJobStmt, cancelJob, jobID)
	return err
}

const countJobsByStatus = `-- name: CountJobsByStatus :many
SELECT status, COUNT(*) AS count
FROM jobs
GROUP BY status
`

type CountJobsByStatusRow struct {
	Status string `json:"status"`
	Count  int64  `json:"count"`
}

// Useful for an admin dashboard or metrics endpoint.
func (q *Queries) CountJobsByStatus(ctx context.Context) ([]CountJobsByStatusRow, error) {
	rows, err := q.query(ctx, q.countJobsByStatusStmt, countJobsByStatus)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CountJobsByStatusRow{}
	for rows.Next() {
		var i CountJobsByStatusRow
		if err := rows.Scan(&i.Status, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createJob = `-- name: CreateJob :one
INSERT INTO jobs (
    owner_user_id,
    owner_replica,
    mapper_path,
    reducer_path,
    input_path,
    output_path,
    num_mappers,
    num_reducers,
    input_format
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9
)
RETURNING job_id, owner_user_id, owner_replica, status, mapper_path, reducer_path, input_path, output_path, num_mappers, num_reducers, input_format, submitted_at, started_at, completed_at, error_message
`

type CreateJobParams struct {
	OwnerUserID  string `json:"owner_user_id"`
	OwnerReplica string `json:"owner_replica"`
	MapperPath   string `json:"mapper_path"`
	ReducerPath  string `json:"reducer_path"`
	InputPath    string `json:"input_path"`
	OutputPath   string `json:"output_path"`
	NumMappers   int32  `json:"num_mappers"`
	NumReducers  int32  `json:"num_reducers"`
	InputFormat  string `json:"input_format"`
}

func (q *Queries) CreateJob(ctx context.Context, arg CreateJobParams) (Job, error) {
	row := q.queryRow(ctx, q.createJobStmt, createJob,
		arg.OwnerUserID,
		arg.OwnerReplica,
		arg.MapperPath,
		arg.ReducerPath,
		arg.InputPath,
		arg.OutputPath,
		arg.NumMappers,
		arg.NumReducers,
		arg.InputFormat,
	)
	var i Job
	err := row.Scan(
		&i.JobID,
		&i.OwnerUserID,
		&i.OwnerReplica,
		&i.Status,
		&i.MapperPath,
		&i.ReducerPath,
		&i.InputPath,
		&i.OutputPath,
		&i.NumMappers,
		&i.NumReducers,
		&i.InputFormat,
		&i.SubmittedAt,
		&i.StartedAt,
		&i.CompletedAt,
		&i.ErrorMessage,
	)
	return i, err
}

const failJob = `-- name: FailJob :exec
UPDATE jobs
SET
    status        = 'FAILED',
    completed_at  = NOW(),
    error_message = $2
WHERE job_id = $1
`

type FailJobParams struct {
	JobID        uuid.UUID      `json:"job_id"`
	ErrorMessage sql.NullString `json:"error_message"`
}

func (q *Queries) FailJob(ctx context.Context, arg FailJobParams) error {
	_, err := q.exec(ctx, q.failJobStmt, failJob, arg.JobID, arg.ErrorMessage)
	return err
}

const getActiveJobsByReplica = `-- name: GetActiveJobsByReplica :many
SELECT job_id, owner_user_id, owner_replica, status, mapper_path, reducer_path, input_path, output_path, num_mappers, num_reducers, input_format, submitted_at, started_at, completed_at, error_message FROM jobs
WHERE owner_replica = $1
  AND status NOT IN ('COMPLETED', 'FAILED', 'CANCELLED')
`

// Used by the Manager on startup to re-attach to in-flight jobs it owns.
func (q *Queries) GetActiveJobsByReplica(ctx context.Context, ownerReplica string) ([]Job, error) {
	rows, err := q.query(ctx, q.getActiveJobsByReplicaStmt, getActiveJobsByReplica, ownerReplica)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Job{}
	for rows.Next() {
		var i Job
		if err := rows.Scan(
			&i.JobID,
			&i.OwnerUserID,
			&i.OwnerReplica,
			&i.Status,
			&i.MapperPath,
			&i.ReducerPath,
			&i.InputPath,
			&i.OutputPath,
			&i.NumMappers,
			&i.NumReducers,
			&i.InputFormat,
			&i.SubmittedAt,
			&i.StartedAt,
			&i.CompletedAt,
			&i.ErrorMessage,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllJobs = `-- name: GetAllJobs :many
SELECT job_id, owner_user_id, owner_replica, status, mapper_path, reducer_path, input_path, output_path, num_mappers, num_reducers, input_format, submitted_at, started_at, completed_at, error_message FROM jobs
ORDER BY submitted_at DESC
`

func (q *Queries) GetAllJobs(ctx context.Context) ([]Job, error) {
	rows, err := q.query(ctx, q.getAllJobsStmt, getAllJobs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Job{}
	for rows.Next() {
		var i Job
		if err := rows.Scan(
			&i.JobID,
			&i.OwnerUserID,
			&i.OwnerReplica,
			&i.Status,
			&i.MapperPath,
			&i.ReducerPath,
			&i.InputPath,
			&i.OutputPath,
			&i.NumMappers,
			&i.NumReducers,
			&i.InputFormat,
			&i.SubmittedAt,
			&i.StartedAt,
			&i.CompletedAt,
			&i.ErrorMessage,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getJob = `-- name: GetJob :one
SELECT job_id, owner_user_id, owner_replica, status, mapper_path, reducer_path, input_path, output_path, num_mappers, num_reducers, input_format, submitted_at, started_at, completed_at, error_message FROM jobs
WHERE job_id = $1
LIMIT 1
`

func (q *Queries) GetJob(ctx context.Context, jobID uuid.UUID) (Job, error) {
	row := q.queryRow(ctx, q.getJobStmt, getJob, jobID)
	var i Job
	err := row.Scan(
		&i.JobID,
		&i.OwnerUserID,
		&i.OwnerReplica,
		&i.Status,
		&i.MapperPath,
		&i.ReducerPath,
		&i.InputPath,
		&i.OutputPath,
		&i.NumMappers,
		&i.NumReducers,
		&i.InputFormat,
		&i.SubmittedAt,
		&i.StartedAt,
		&i.CompletedAt,
		&i.ErrorMessage,
	)
	return i, err
}

const getJobsByUser = `-- name: GetJobsByUser :many
SELECT job_id, owner_user_id, owner_replica, status, mapper_path, reducer_path, input_path, output_path, num_mappers, num_reducers, input_format, submitted_at, started_at, completed_at, error_message FROM jobs
WHERE owner_user_id = $1
ORDER BY submitted_at DESC
`

func (q *Queries) GetJobsByUser(ctx context.Context, ownerUserID string) ([]Job, error) {
	rows, err := q.query(ctx, q.getJobsByUserStmt, getJobsByUser, ownerUserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Job{}
	for rows.Next() {
		var i Job
		if err := rows.Scan(
			&i.JobID,
			&i.OwnerUserID,
			&i.OwnerReplica,
			&i.Status,
			&i.MapperPath,
			&i.ReducerPath,
			&i.InputPath,
			&i.OutputPath,
			&i.NumMappers,
			&i.NumReducers,
			&i.InputFormat,
			&i.SubmittedAt,
			&i.StartedAt,
			&i.CompletedAt,
			&i.ErrorMessage,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateJobStatus = `-- name: UpdateJobStatus :exec
UPDATE jobs
SET
    status       = $2,
    started_at   = CASE
                     WHEN $2 = 'MAP_PHASE' AND started_at IS NULL
                     THEN NOW()
                     ELSE started_at
                   END,
    completed_at = CASE
                     WHEN $2 IN ('COMPLETED', 'FAILED', 'CANCELLED')
                     THEN NOW()
                     ELSE completed_at
                   END
WHERE job_id = $1
`

type UpdateJobStatusParams struct {
	JobID  uuid.UUID `json:"job_id"`
	Status string    `json:"status"`
}

func (q *Queries) UpdateJobStatus(ctx context.Context, arg UpdateJobStatusParams) error {
	_, err := q.exec(ctx, q.updateJobStatusStmt, updateJobStatus, arg.JobID, arg.Status)
	return err
}
