// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: jobs.sql

package db

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
	"github.com/sqlc-dev/pqtype"
)

const cancelJob = `-- name: CancelJob :exec
UPDATE jobs
SET
    status       = 'CANCELLED',
    completed_at = NOW()
WHERE job_id = $1
  AND status NOT IN ('COMPLETED', 'FAILED', 'CANCELLED')
`

func (q *Queries) CancelJob(ctx context.Context, jobID uuid.UUID) error {
	_, err := q.exec(ctx, q.cancelJobStmt, cancelJob, jobID)
	return err
}

const countJobsByStatus = `-- name: CountJobsByStatus :many
SELECT status, COUNT(*) AS count
FROM jobs
GROUP BY status
`

type CountJobsByStatusRow struct {
	Status string `json:"status"`
	Count  int64  `json:"count"`
}

// Useful for an admin dashboard or metrics endpoint.
func (q *Queries) CountJobsByStatus(ctx context.Context) ([]CountJobsByStatusRow, error) {
	rows, err := q.query(ctx, q.countJobsByStatusStmt, countJobsByStatus)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CountJobsByStatusRow{}
	for rows.Next() {
		var i CountJobsByStatusRow
		if err := rows.Scan(&i.Status, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createJob = `-- name: CreateJob :one
INSERT INTO jobs (
    owner_user_id,
    owner_replica,
    mapper_path,
    reducer_path,
    input_path,
    output_path,
    num_mappers,
    num_reducers,
    input_format,
    workflow_id,
    stage_name,
    input_bucket,
    output_bucket,
    condition
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14
)
RETURNING job_id, owner_user_id, owner_replica, status, mapper_path, reducer_path, input_path, output_path, num_mappers, num_reducers, input_format, submitted_at, started_at, completed_at, error_message, workflow_id, stage_name, input_bucket, output_bucket, output_records, condition
`

type CreateJobParams struct {
	OwnerUserID  string                `json:"owner_user_id"`
	OwnerReplica string                `json:"owner_replica"`
	MapperPath   string                `json:"mapper_path"`
	ReducerPath  string                `json:"reducer_path"`
	InputPath    string                `json:"input_path"`
	OutputPath   string                `json:"output_path"`
	NumMappers   int32                 `json:"num_mappers"`
	NumReducers  int32                 `json:"num_reducers"`
	InputFormat  string                `json:"input_format"`
	WorkflowID   uuid.NullUUID         `json:"workflow_id"`
	StageName    sql.NullString        `json:"stage_name"`
	InputBucket  string                `json:"input_bucket"`
	OutputBucket string                `json:"output_bucket"`
	Condition    pqtype.NullRawMessage `json:"condition"`
}

func (q *Queries) CreateJob(ctx context.Context, arg CreateJobParams) (Job, error) {
	row := q.queryRow(ctx, q.createJobStmt, createJob,
		arg.OwnerUserID,
		arg.OwnerReplica,
		arg.MapperPath,
		arg.ReducerPath,
		arg.InputPath,
		arg.OutputPath,
		arg.NumMappers,
		arg.NumReducers,
		arg.InputFormat,
		arg.WorkflowID,
		arg.StageName,
		arg.InputBucket,
		arg.OutputBucket,
		arg.Condition,
	)
	var i Job
	err := row.Scan(
		&i.JobID,
		&i.OwnerUserID,
		&i.OwnerReplica,
		&i.Status,
		&i.MapperPath,
		&i.ReducerPath,
		&i.InputPath,
		&i.OutputPath,
		&i.NumMappers,
		&i.NumReducers,
		&i.InputFormat,
		&i.SubmittedAt,
		&i.StartedAt,
		&i.CompletedAt,
		&i.ErrorMessage,
		&i.WorkflowID,
		&i.StageName,
		&i.InputBucket,
		&i.OutputBucket,
		&i.OutputRecords,
		&i.Condition,
	)
	return i, err
}

const deleteJob = `-- name: DeleteJob :exec
DELETE FROM jobs
WHERE job_id = $1
`

func (q *Queries) DeleteJob(ctx context.Context, jobID uuid.UUID) error {
	_, err := q.exec(ctx, q.deleteJobStmt, deleteJob, jobID)
	return err
}

const failJob = `-- name: FailJob :exec
UPDATE jobs
SET
    status        = 'FAILED',
    completed_at  = NOW(),
    error_message = $2
WHERE job_id = $1
`

type FailJobParams struct {
	JobID        uuid.UUID      `json:"job_id"`
	ErrorMessage sql.NullString `json:"error_message"`
}

func (q *Queries) FailJob(ctx context.Context, arg FailJobParams) error {
	_, err := q.exec(ctx, q.failJobStmt, failJob, arg.JobID, arg.ErrorMessage)
	return err
}

const getActiveJobsByReplica = `-- name: GetActiveJobsByReplica :many
SELECT job_id, owner_user_id, owner_replica, status, mapper_path, reducer_path, input_path, output_path, num_mappers, num_reducers, input_format, submitted_at, started_at, completed_at, error_message, workflow_id, stage_name, input_bucket, output_bucket, output_records, condition FROM jobs
WHERE owner_replica = $1
  AND status NOT IN ('COMPLETED', 'FAILED', 'CANCELLED')
`

// Used by the Manager on startup to re-attach to in-flight jobs it owns.
func (q *Queries) GetActiveJobsByReplica(ctx context.Context, ownerReplica string) ([]Job, error) {
	rows, err := q.query(ctx, q.getActiveJobsByReplicaStmt, getActiveJobsByReplica, ownerReplica)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Job{}
	for rows.Next() {
		var i Job
		if err := rows.Scan(
			&i.JobID,
			&i.OwnerUserID,
			&i.OwnerReplica,
			&i.Status,
			&i.MapperPath,
			&i.ReducerPath,
			&i.InputPath,
			&i.OutputPath,
			&i.NumMappers,
			&i.NumReducers,
			&i.InputFormat,
			&i.SubmittedAt,
			&i.StartedAt,
			&i.CompletedAt,
			&i.ErrorMessage,
			&i.WorkflowID,
			&i.StageName,
			&i.InputBucket,
			&i.OutputBucket,
			&i.OutputRecords,
			&i.Condition,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllJobs = `-- name: GetAllJobs :many
SELECT job_id, owner_user_id, owner_replica, status, mapper_path, reducer_path, input_path, output_path, num_mappers, num_reducers, input_format, submitted_at, started_at, completed_at, error_message, workflow_id, stage_name, input_bucket, output_bucket, output_records, condition FROM jobs
ORDER BY submitted_at DESC
`

func (q *Queries) GetAllJobs(ctx context.Context) ([]Job, error) {
	rows, err := q.query(ctx, q.getAllJobsStmt, getAllJobs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Job{}
	for rows.Next() {
		var i Job
		if err := rows.Scan(
			&i.JobID,
			&i.OwnerUserID,
			&i.OwnerReplica,
			&i.Status,
			&i.MapperPath,
			&i.ReducerPath,
			&i.InputPath,
			&i.OutputPath,
			&i.NumMappers,
			&i.NumReducers,
			&i.InputFormat,
			&i.SubmittedAt,
			&i.StartedAt,
			&i.CompletedAt,
			&i.ErrorMessage,
			&i.WorkflowID,
			&i.StageName,
			&i.InputBucket,
			&i.OutputBucket,
			&i.OutputRecords,
			&i.Condition,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getJob = `-- name: GetJob :one
SELECT job_id, owner_user_id, owner_replica, status, mapper_path, reducer_path, input_path, output_path, num_mappers, num_reducers, input_format, submitted_at, started_at, completed_at, error_message, workflow_id, stage_name, input_bucket, output_bucket, output_records, condition FROM jobs
WHERE job_id = $1
LIMIT 1
`

func (q *Queries) GetJob(ctx context.Context, jobID uuid.UUID) (Job, error) {
	row := q.queryRow(ctx, q.getJobStmt, getJob, jobID)
	var i Job
	err := row.Scan(
		&i.JobID,
		&i.OwnerUserID,
		&i.OwnerReplica,
		&i.Status,
		&i.MapperPath,
		&i.ReducerPath,
		&i.InputPath,
		&i.OutputPath,
		&i.NumMappers,
		&i.NumReducers,
		&i.InputFormat,
		&i.SubmittedAt,
		&i.StartedAt,
		&i.CompletedAt,
		&i.ErrorMessage,
		&i.WorkflowID,
		&i.StageName,
		&i.InputBucket,
		&i.OutputBucket,
		&i.OutputRecords,
		&i.Condition,
	)
	return i, err
}

const getJobsByUser = `-- name: GetJobsByUser :many
SELECT job_id, owner_user_id, owner_replica, status, mapper_path, reducer_path, input_path, output_path, num_mappers, num_reducers, input_format, submitted_at, started_at, completed_at, error_message, workflow_id, stage_name, input_bucket, output_bucket, output_records, condition FROM jobs
WHERE owner_user_id = $1
ORDER BY submitted_at DESC
`

func (q *Queries) GetJobsByUser(ctx context.Context, ownerUserID string) ([]Job, error) {
	rows, err := q.query(ctx, q.getJobsByUserStmt, getJobsByUser, ownerUserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Job{}
	for rows.Next() {
		var i Job
		if err := rows.Scan(
			&i.JobID,
			&i.OwnerUserID,
			&i.OwnerReplica,
			&i.Status,
			&i.MapperPath,
			&i.ReducerPath,
			&i.InputPath,
			&i.OutputPath,
			&i.NumMappers,
			&i.NumReducers,
			&i.InputFormat,
			&i.SubmittedAt,
			&i.StartedAt,
			&i.CompletedAt,
			&i.ErrorMessage,
			&i.WorkflowID,
			&i.StageName,
			&i.InputBucket,
			&i.OutputBucket,
			&i.OutputRecords,
			&i.Condition,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const incrementJobOutputRecords = `-- name: IncrementJobOutputRecords :exec
UPDATE jobs
SET output_records = output_records + $2
WHERE job_id = $1
`

type IncrementJobOutputRecordsParams struct {
	JobID         uuid.UUID `json:"job_id"`
	OutputRecords int64     `json:"output_records"`
}

func (q *Queries) IncrementJobOutputRecords(ctx context.Context, arg IncrementJobOutputRecordsParams) error {
	_, err := q.exec(ctx, q.incrementJobOutputRecordsStmt, incrementJobOutputRecords, arg.JobID, arg.OutputRecords)
	return err
}

const updateJobInputAndStatus = `-- name: UpdateJobInputAndStatus :exec
UPDATE jobs
SET 
    input_path = $2,
    input_bucket = $3,
    status = $4
WHERE job_id = $1
`

type UpdateJobInputAndStatusParams struct {
	JobID       uuid.UUID `json:"job_id"`
	InputPath   string    `json:"input_path"`
	InputBucket string    `json:"input_bucket"`
	Status      string    `json:"status"`
}

func (q *Queries) UpdateJobInputAndStatus(ctx context.Context, arg UpdateJobInputAndStatusParams) error {
	_, err := q.exec(ctx, q.updateJobInputAndStatusStmt, updateJobInputAndStatus,
		arg.JobID,
		arg.InputPath,
		arg.InputBucket,
		arg.Status,
	)
	return err
}

const updateJobMapperPath = `-- name: UpdateJobMapperPath :exec
UPDATE jobs
SET mapper_path = $2
WHERE job_id = $1
`

type UpdateJobMapperPathParams struct {
	JobID      uuid.UUID `json:"job_id"`
	MapperPath string    `json:"mapper_path"`
}

func (q *Queries) UpdateJobMapperPath(ctx context.Context, arg UpdateJobMapperPathParams) error {
	_, err := q.exec(ctx, q.updateJobMapperPathStmt, updateJobMapperPath, arg.JobID, arg.MapperPath)
	return err
}

const updateJobReducerPath = `-- name: UpdateJobReducerPath :exec
UPDATE jobs
SET reducer_path = $2
WHERE job_id = $1
`

type UpdateJobReducerPathParams struct {
	JobID       uuid.UUID `json:"job_id"`
	ReducerPath string    `json:"reducer_path"`
}

func (q *Queries) UpdateJobReducerPath(ctx context.Context, arg UpdateJobReducerPathParams) error {
	_, err := q.exec(ctx, q.updateJobReducerPathStmt, updateJobReducerPath, arg.JobID, arg.ReducerPath)
	return err
}

const updateJobStatus = `-- name: UpdateJobStatus :exec
UPDATE jobs
SET
    status       = $2,
    started_at   = CASE
                     WHEN $2::varchar IN ('BUILDING', 'MAP_PHASE') AND started_at IS NULL
                     THEN NOW()
                     ELSE started_at
                   END,
    completed_at = CASE
                     WHEN $2::varchar IN ('COMPLETED', 'FAILED', 'CANCELLED')
                     THEN NOW()
                     ELSE completed_at
                   END
WHERE job_id = $1
`

type UpdateJobStatusParams struct {
	JobID  uuid.UUID `json:"job_id"`
	Status string    `json:"status"`
}

func (q *Queries) UpdateJobStatus(ctx context.Context, arg UpdateJobStatusParams) error {
	_, err := q.exec(ctx, q.updateJobStatusStmt, updateJobStatus, arg.JobID, arg.Status)
	return err
}
