// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: map_tasks.sql

package db

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
	"github.com/sqlc-dev/pqtype"
)

const countMapTasksByStatus = `-- name: CountMapTasksByStatus :one
SELECT
    COUNT(*) FILTER (WHERE status = 'COMPLETED') AS completed,
    COUNT(*) FILTER (WHERE status = 'FAILED')    AS failed,
    COUNT(*)                                      AS total
FROM map_tasks
WHERE job_id = $1
`

type CountMapTasksByStatusRow struct {
	Completed int64 `json:"completed"`
	Failed    int64 `json:"failed"`
	Total     int64 `json:"total"`
}

// Atomically read how many tasks are COMPLETED vs total.
// Used by the Manager to decide when to advance to REDUCE_PHASE.
func (q *Queries) CountMapTasksByStatus(ctx context.Context, jobID uuid.UUID) (CountMapTasksByStatusRow, error) {
	row := q.queryRow(ctx, q.countMapTasksByStatusStmt, countMapTasksByStatus, jobID)
	var i CountMapTasksByStatusRow
	err := row.Scan(&i.Completed, &i.Failed, &i.Total)
	return i, err
}

const createMapTask = `-- name: CreateMapTask :one
INSERT INTO map_tasks (
    job_id,
    task_index,
    input_file,
    input_offset,
    input_length
) VALUES (
    $1, $2, $3, $4, $5
)
RETURNING task_id, job_id, task_index, status, input_file, input_offset, input_length, k8s_job_name, worker_pod, retry_count, started_at, completed_at, output_locations
`

type CreateMapTaskParams struct {
	JobID       uuid.UUID `json:"job_id"`
	TaskIndex   int32     `json:"task_index"`
	InputFile   string    `json:"input_file"`
	InputOffset int64     `json:"input_offset"`
	InputLength int64     `json:"input_length"`
}

func (q *Queries) CreateMapTask(ctx context.Context, arg CreateMapTaskParams) (MapTask, error) {
	row := q.queryRow(ctx, q.createMapTaskStmt, createMapTask,
		arg.JobID,
		arg.TaskIndex,
		arg.InputFile,
		arg.InputOffset,
		arg.InputLength,
	)
	var i MapTask
	err := row.Scan(
		&i.TaskID,
		&i.JobID,
		&i.TaskIndex,
		&i.Status,
		&i.InputFile,
		&i.InputOffset,
		&i.InputLength,
		&i.K8sJobName,
		&i.WorkerPod,
		&i.RetryCount,
		&i.StartedAt,
		&i.CompletedAt,
		&i.OutputLocations,
	)
	return i, err
}

const getMapTask = `-- name: GetMapTask :one
SELECT task_id, job_id, task_index, status, input_file, input_offset, input_length, k8s_job_name, worker_pod, retry_count, started_at, completed_at, output_locations FROM map_tasks
WHERE task_id = $1
LIMIT 1
`

func (q *Queries) GetMapTask(ctx context.Context, taskID uuid.UUID) (MapTask, error) {
	row := q.queryRow(ctx, q.getMapTaskStmt, getMapTask, taskID)
	var i MapTask
	err := row.Scan(
		&i.TaskID,
		&i.JobID,
		&i.TaskIndex,
		&i.Status,
		&i.InputFile,
		&i.InputOffset,
		&i.InputLength,
		&i.K8sJobName,
		&i.WorkerPod,
		&i.RetryCount,
		&i.StartedAt,
		&i.CompletedAt,
		&i.OutputLocations,
	)
	return i, err
}

const getMapTaskOutputLocations = `-- name: GetMapTaskOutputLocations :many
SELECT task_index, output_locations
FROM map_tasks
WHERE job_id = $1
  AND status = 'COMPLETED'
ORDER BY task_index
`

type GetMapTaskOutputLocationsRow struct {
	TaskIndex       int32                 `json:"task_index"`
	OutputLocations pqtype.NullRawMessage `json:"output_locations"`
}

// Used by the Manager when building the reduce task inputs.
// Returns all completed map tasks and their output_locations for a job.
func (q *Queries) GetMapTaskOutputLocations(ctx context.Context, jobID uuid.UUID) ([]GetMapTaskOutputLocationsRow, error) {
	rows, err := q.query(ctx, q.getMapTaskOutputLocationsStmt, getMapTaskOutputLocations, jobID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetMapTaskOutputLocationsRow{}
	for rows.Next() {
		var i GetMapTaskOutputLocationsRow
		if err := rows.Scan(&i.TaskIndex, &i.OutputLocations); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMapTasksByJob = `-- name: GetMapTasksByJob :many
SELECT task_id, job_id, task_index, status, input_file, input_offset, input_length, k8s_job_name, worker_pod, retry_count, started_at, completed_at, output_locations FROM map_tasks
WHERE job_id = $1
ORDER BY task_index
`

func (q *Queries) GetMapTasksByJob(ctx context.Context, jobID uuid.UUID) ([]MapTask, error) {
	rows, err := q.query(ctx, q.getMapTasksByJobStmt, getMapTasksByJob, jobID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MapTask{}
	for rows.Next() {
		var i MapTask
		if err := rows.Scan(
			&i.TaskID,
			&i.JobID,
			&i.TaskIndex,
			&i.Status,
			&i.InputFile,
			&i.InputOffset,
			&i.InputLength,
			&i.K8sJobName,
			&i.WorkerPod,
			&i.RetryCount,
			&i.StartedAt,
			&i.CompletedAt,
			&i.OutputLocations,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMapTasksByJobAndStatus = `-- name: GetMapTasksByJobAndStatus :many
SELECT task_id, job_id, task_index, status, input_file, input_offset, input_length, k8s_job_name, worker_pod, retry_count, started_at, completed_at, output_locations FROM map_tasks
WHERE job_id = $1
  AND status = $2
ORDER BY task_index
`

type GetMapTasksByJobAndStatusParams struct {
	JobID  uuid.UUID `json:"job_id"`
	Status string    `json:"status"`
}

func (q *Queries) GetMapTasksByJobAndStatus(ctx context.Context, arg GetMapTasksByJobAndStatusParams) ([]MapTask, error) {
	rows, err := q.query(ctx, q.getMapTasksByJobAndStatusStmt, getMapTasksByJobAndStatus, arg.JobID, arg.Status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MapTask{}
	for rows.Next() {
		var i MapTask
		if err := rows.Scan(
			&i.TaskID,
			&i.JobID,
			&i.TaskIndex,
			&i.Status,
			&i.InputFile,
			&i.InputOffset,
			&i.InputLength,
			&i.K8sJobName,
			&i.WorkerPod,
			&i.RetryCount,
			&i.StartedAt,
			&i.CompletedAt,
			&i.OutputLocations,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPendingMapTasks = `-- name: GetPendingMapTasks :many
SELECT task_id, job_id, task_index, status, input_file, input_offset, input_length, k8s_job_name, worker_pod, retry_count, started_at, completed_at, output_locations FROM map_tasks
WHERE job_id = $1
  AND status = 'PENDING'
ORDER BY task_index
LIMIT $2
`

type GetPendingMapTasksParams struct {
	JobID uuid.UUID `json:"job_id"`
	Limit int32     `json:"limit"`
}

// Used by the Manager to find tasks ready to dispatch as K8s Jobs.
func (q *Queries) GetPendingMapTasks(ctx context.Context, arg GetPendingMapTasksParams) ([]MapTask, error) {
	rows, err := q.query(ctx, q.getPendingMapTasksStmt, getPendingMapTasks, arg.JobID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MapTask{}
	for rows.Next() {
		var i MapTask
		if err := rows.Scan(
			&i.TaskID,
			&i.JobID,
			&i.TaskIndex,
			&i.Status,
			&i.InputFile,
			&i.InputOffset,
			&i.InputLength,
			&i.K8sJobName,
			&i.WorkerPod,
			&i.RetryCount,
			&i.StartedAt,
			&i.CompletedAt,
			&i.OutputLocations,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getStaleRunningMapTasks = `-- name: GetStaleRunningMapTasks :many
SELECT task_id, job_id, task_index, status, input_file, input_offset, input_length, k8s_job_name, worker_pod, retry_count, started_at, completed_at, output_locations FROM map_tasks
WHERE status = 'RUNNING'
  AND started_at < NOW() - ($1 || ' seconds')::INTERVAL
`

// Used by the timeout watchdog: find RUNNING tasks older than N seconds.
func (q *Queries) GetStaleRunningMapTasks(ctx context.Context, dollar_1 sql.NullString) ([]MapTask, error) {
	rows, err := q.query(ctx, q.getStaleRunningMapTasksStmt, getStaleRunningMapTasks, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MapTask{}
	for rows.Next() {
		var i MapTask
		if err := rows.Scan(
			&i.TaskID,
			&i.JobID,
			&i.TaskIndex,
			&i.Status,
			&i.InputFile,
			&i.InputOffset,
			&i.InputLength,
			&i.K8sJobName,
			&i.WorkerPod,
			&i.RetryCount,
			&i.StartedAt,
			&i.CompletedAt,
			&i.OutputLocations,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const incrementMapTaskRetry = `-- name: IncrementMapTaskRetry :exec
UPDATE map_tasks
SET
    retry_count  = retry_count + 1,
    status       = 'PENDING',
    k8s_job_name = NULL,
    worker_pod   = NULL,
    started_at   = NULL
WHERE task_id = $1
`

func (q *Queries) IncrementMapTaskRetry(ctx context.Context, taskID uuid.UUID) error {
	_, err := q.exec(ctx, q.incrementMapTaskRetryStmt, incrementMapTaskRetry, taskID)
	return err
}

const markMapTaskCompleted = `-- name: MarkMapTaskCompleted :exec
UPDATE map_tasks
SET
    status           = 'COMPLETED',
    output_locations = $2,
    completed_at     = NOW()
WHERE task_id = $1
`

type MarkMapTaskCompletedParams struct {
	TaskID          uuid.UUID             `json:"task_id"`
	OutputLocations pqtype.NullRawMessage `json:"output_locations"`
}

// Called when the worker POSTs to /tasks/:id/complete.
// output_locations is a JSONB array: [{"reducer_index":0,"path":"..."}]
func (q *Queries) MarkMapTaskCompleted(ctx context.Context, arg MarkMapTaskCompletedParams) error {
	_, err := q.exec(ctx, q.markMapTaskCompletedStmt, markMapTaskCompleted, arg.TaskID, arg.OutputLocations)
	return err
}

const markMapTaskFailed = `-- name: MarkMapTaskFailed :exec
UPDATE map_tasks
SET
    status      = 'FAILED',
    completed_at = NOW()
WHERE task_id = $1
`

func (q *Queries) MarkMapTaskFailed(ctx context.Context, taskID uuid.UUID) error {
	_, err := q.exec(ctx, q.markMapTaskFailedStmt, markMapTaskFailed, taskID)
	return err
}

const markMapTaskRunning = `-- name: MarkMapTaskRunning :exec
UPDATE map_tasks
SET
    status       = 'RUNNING',
    k8s_job_name = $2,
    started_at   = NOW()
WHERE task_id = $1
`

type MarkMapTaskRunningParams struct {
	TaskID     uuid.UUID      `json:"task_id"`
	K8sJobName sql.NullString `json:"k8s_job_name"`
}

// Called when the Manager creates the K8s Job for this task.
func (q *Queries) MarkMapTaskRunning(ctx context.Context, arg MarkMapTaskRunningParams) error {
	_, err := q.exec(ctx, q.markMapTaskRunningStmt, markMapTaskRunning, arg.TaskID, arg.K8sJobName)
	return err
}
