// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package db

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
	"github.com/sqlc-dev/pqtype"
)

type Job struct {
	JobID        uuid.UUID      `json:"job_id"`
	OwnerUserID  string         `json:"owner_user_id"`
	OwnerReplica string         `json:"owner_replica"`
	Status       string         `json:"status"`
	MapperPath   string         `json:"mapper_path"`
	ReducerPath  string         `json:"reducer_path"`
	InputPath    string         `json:"input_path"`
	OutputPath   string         `json:"output_path"`
	NumMappers   int32          `json:"num_mappers"`
	NumReducers  int32          `json:"num_reducers"`
	InputFormat  string         `json:"input_format"`
	SubmittedAt  time.Time      `json:"submitted_at"`
	StartedAt    sql.NullTime   `json:"started_at"`
	CompletedAt  sql.NullTime   `json:"completed_at"`
	ErrorMessage sql.NullString `json:"error_message"`
}

type MapTask struct {
	TaskID          uuid.UUID             `json:"task_id"`
	JobID           uuid.UUID             `json:"job_id"`
	TaskIndex       int32                 `json:"task_index"`
	Status          string                `json:"status"`
	InputFile       string                `json:"input_file"`
	InputOffset     int64                 `json:"input_offset"`
	InputLength     int64                 `json:"input_length"`
	K8sJobName      sql.NullString        `json:"k8s_job_name"`
	WorkerPod       sql.NullString        `json:"worker_pod"`
	RetryCount      int32                 `json:"retry_count"`
	StartedAt       sql.NullTime          `json:"started_at"`
	CompletedAt     sql.NullTime          `json:"completed_at"`
	OutputLocations pqtype.NullRawMessage `json:"output_locations"`
}

type ReduceTask struct {
	TaskID      uuid.UUID      `json:"task_id"`
	JobID       uuid.UUID      `json:"job_id"`
	TaskIndex   int32          `json:"task_index"`
	Status      string         `json:"status"`
	K8sJobName  sql.NullString `json:"k8s_job_name"`
	WorkerPod   sql.NullString `json:"worker_pod"`
	RetryCount  int32          `json:"retry_count"`
	StartedAt   sql.NullTime   `json:"started_at"`
	CompletedAt sql.NullTime   `json:"completed_at"`
	OutputPath  sql.NullString `json:"output_path"`
}

type User struct {
	UserID       uuid.UUID      `json:"user_id"`
	Username     string         `json:"username"`
	PasswordHash string         `json:"password_hash"`
	Role         string         `json:"role"`
	Email        sql.NullString `json:"email"`
	CreateAt     time.Time      `json:"create_at"`
}
