// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package db

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
	"github.com/sqlc-dev/pqtype"
)

type Job struct {
	JobID         uuid.UUID             `json:"job_id"`
	OwnerUserID   string                `json:"owner_user_id"`
	OwnerReplica  string                `json:"owner_replica"`
	Status        string                `json:"status"`
	MapperPath    string                `json:"mapper_path"`
	ReducerPath   string                `json:"reducer_path"`
	InputPath     string                `json:"input_path"`
	OutputPath    string                `json:"output_path"`
	NumMappers    int32                 `json:"num_mappers"`
	NumReducers   int32                 `json:"num_reducers"`
	InputFormat   string                `json:"input_format"`
	SubmittedAt   time.Time             `json:"submitted_at"`
	StartedAt     sql.NullTime          `json:"started_at"`
	CompletedAt   sql.NullTime          `json:"completed_at"`
	ErrorMessage  sql.NullString        `json:"error_message"`
	WorkflowID    uuid.NullUUID         `json:"workflow_id"`
	StageName     sql.NullString        `json:"stage_name"`
	InputBucket   string                `json:"input_bucket"`
	OutputBucket  string                `json:"output_bucket"`
	OutputRecords int64                 `json:"output_records"`
	Condition     pqtype.NullRawMessage `json:"condition"`
}

type MapTask struct {
	TaskID          uuid.UUID             `json:"task_id"`
	JobID           uuid.UUID             `json:"job_id"`
	TaskIndex       int32                 `json:"task_index"`
	Status          string                `json:"status"`
	InputFile       string                `json:"input_file"`
	InputOffset     int64                 `json:"input_offset"`
	InputLength     int64                 `json:"input_length"`
	K8sJobName      sql.NullString        `json:"k8s_job_name"`
	WorkerPod       sql.NullString        `json:"worker_pod"`
	RetryCount      int32                 `json:"retry_count"`
	StartedAt       sql.NullTime          `json:"started_at"`
	CompletedAt     sql.NullTime          `json:"completed_at"`
	OutputLocations pqtype.NullRawMessage `json:"output_locations"`
}

type PluginCache struct {
	SourceHash string    `json:"source_hash"`
	BinaryPath string    `json:"binary_path"`
	LastUsedAt time.Time `json:"last_used_at"`
}

type ReduceTask struct {
	TaskID      uuid.UUID      `json:"task_id"`
	JobID       uuid.UUID      `json:"job_id"`
	TaskIndex   int32          `json:"task_index"`
	Status      string         `json:"status"`
	K8sJobName  sql.NullString `json:"k8s_job_name"`
	WorkerPod   sql.NullString `json:"worker_pod"`
	RetryCount  int32          `json:"retry_count"`
	StartedAt   sql.NullTime   `json:"started_at"`
	CompletedAt sql.NullTime   `json:"completed_at"`
	OutputPath  sql.NullString `json:"output_path"`
}

type Workflow struct {
	WorkflowID  uuid.UUID `json:"workflow_id"`
	Name        string    `json:"name"`
	Status      string    `json:"status"`
	OwnerUserID string    `json:"owner_user_id"`
	CreatedAt   time.Time `json:"created_at"`
}

type WorkflowDependency struct {
	WorkflowID uuid.UUID `json:"workflow_id"`
	StageName  string    `json:"stage_name"`
	DependsOn  string    `json:"depends_on"`
	CreatedAt  time.Time `json:"created_at"`
}
