// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: plugin_cache.sql

package db

import (
	"context"
	"database/sql"
)

const deleteCachedPlugin = `-- name: DeleteCachedPlugin :exec
DELETE FROM plugin_cache
WHERE source_hash = $1
`

func (q *Queries) DeleteCachedPlugin(ctx context.Context, sourceHash string) error {
	_, err := q.exec(ctx, q.deleteCachedPluginStmt, deleteCachedPlugin, sourceHash)
	return err
}

const getCachedPlugin = `-- name: GetCachedPlugin :one
SELECT source_hash, binary_path, last_used_at FROM plugin_cache
WHERE source_hash = $1
LIMIT 1
`

func (q *Queries) GetCachedPlugin(ctx context.Context, sourceHash string) (PluginCache, error) {
	row := q.queryRow(ctx, q.getCachedPluginStmt, getCachedPlugin, sourceHash)
	var i PluginCache
	err := row.Scan(&i.SourceHash, &i.BinaryPath, &i.LastUsedAt)
	return i, err
}

const listStalePlugins = `-- name: ListStalePlugins :many
SELECT source_hash, binary_path, last_used_at FROM plugin_cache
WHERE last_used_at < NOW() - ($1 || ' seconds')::INTERVAL
`

func (q *Queries) ListStalePlugins(ctx context.Context, dollar_1 sql.NullString) ([]PluginCache, error) {
	rows, err := q.query(ctx, q.listStalePluginsStmt, listStalePlugins, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PluginCache{}
	for rows.Next() {
		var i PluginCache
		if err := rows.Scan(&i.SourceHash, &i.BinaryPath, &i.LastUsedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePluginLastUsed = `-- name: UpdatePluginLastUsed :exec
UPDATE plugin_cache
SET last_used_at = NOW()
WHERE source_hash = $1
`

func (q *Queries) UpdatePluginLastUsed(ctx context.Context, sourceHash string) error {
	_, err := q.exec(ctx, q.updatePluginLastUsedStmt, updatePluginLastUsed, sourceHash)
	return err
}

const upsertCachedPlugin = `-- name: UpsertCachedPlugin :exec
INSERT INTO plugin_cache (source_hash, binary_path, last_used_at)
VALUES ($1, $2, NOW())
ON CONFLICT (source_hash) 
DO UPDATE SET 
    last_used_at = NOW(),
    binary_path = EXCLUDED.binary_path
`

type UpsertCachedPluginParams struct {
	SourceHash string `json:"source_hash"`
	BinaryPath string `json:"binary_path"`
}

func (q *Queries) UpsertCachedPlugin(ctx context.Context, arg UpsertCachedPluginParams) error {
	_, err := q.exec(ctx, q.upsertCachedPluginStmt, upsertCachedPlugin, arg.SourceHash, arg.BinaryPath)
	return err
}
