// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package db

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

type Querier interface {
	CancelJob(ctx context.Context, jobID uuid.UUID) error
	// Useful for an admin dashboard or metrics endpoint.
	CountJobsByStatus(ctx context.Context) ([]CountJobsByStatusRow, error)
	// Atomically read how many tasks are COMPLETED vs total.
	// Used by the Manager to decide when to advance to REDUCE_PHASE.
	CountMapTasksByStatus(ctx context.Context, jobID uuid.UUID) (CountMapTasksByStatusRow, error)
	// Used by the Manager to decide when the job is fully COMPLETED.
	CountReduceTasksByStatus(ctx context.Context, jobID uuid.UUID) (CountReduceTasksByStatusRow, error)
	CreateJob(ctx context.Context, arg CreateJobParams) (Job, error)
	CreateMapTask(ctx context.Context, arg CreateMapTaskParams) (MapTask, error)
	CreateReduceTask(ctx context.Context, arg CreateReduceTaskParams) (ReduceTask, error)
	FailJob(ctx context.Context, arg FailJobParams) error
	// Used by the Manager on startup to re-attach to in-flight jobs it owns.
	GetActiveJobsByReplica(ctx context.Context, ownerReplica string) ([]Job, error)
	GetAllJobs(ctx context.Context) ([]Job, error)
	GetJob(ctx context.Context, jobID uuid.UUID) (Job, error)
	GetJobsByUser(ctx context.Context, ownerUserID string) ([]Job, error)
	GetMapTask(ctx context.Context, taskID uuid.UUID) (MapTask, error)
	// Used by the Manager when building the reduce task inputs.
	// Returns all completed map tasks and their output_locations for a job.
	GetMapTaskOutputLocations(ctx context.Context, jobID uuid.UUID) ([]GetMapTaskOutputLocationsRow, error)
	GetMapTasksByJob(ctx context.Context, jobID uuid.UUID) ([]MapTask, error)
	GetMapTasksByJobAndStatus(ctx context.Context, arg GetMapTasksByJobAndStatusParams) ([]MapTask, error)
	// Used by the Manager to find tasks ready to dispatch as K8s Jobs.
	GetPendingMapTasks(ctx context.Context, arg GetPendingMapTasksParams) ([]MapTask, error)
	// Used by the Manager to find tasks ready to dispatch as K8s Jobs.
	GetPendingReduceTasks(ctx context.Context, arg GetPendingReduceTasksParams) ([]ReduceTask, error)
	GetReduceTask(ctx context.Context, taskID uuid.UUID) (ReduceTask, error)
	// Used to build the final job output listing.
	GetReduceTaskOutputPaths(ctx context.Context, jobID uuid.UUID) ([]GetReduceTaskOutputPathsRow, error)
	GetReduceTasksByJob(ctx context.Context, jobID uuid.UUID) ([]ReduceTask, error)
	GetReduceTasksByJobAndStatus(ctx context.Context, arg GetReduceTasksByJobAndStatusParams) ([]ReduceTask, error)
	// Used by the timeout watchdog: find RUNNING tasks older than N seconds.
	GetStaleRunningMapTasks(ctx context.Context, dollar_1 sql.NullString) ([]MapTask, error)
	// Used by the timeout watchdog.
	GetStaleRunningReduceTasks(ctx context.Context, dollar_1 sql.NullString) ([]ReduceTask, error)
	IncrementMapTaskRetry(ctx context.Context, taskID uuid.UUID) error
	IncrementReduceTaskRetry(ctx context.Context, taskID uuid.UUID) error
	// Called when the worker POSTs to /tasks/:id/complete.
	// output_locations is a JSONB array: [{"reducer_index":0,"path":"..."}]
	MarkMapTaskCompleted(ctx context.Context, arg MarkMapTaskCompletedParams) error
	MarkMapTaskFailed(ctx context.Context, taskID uuid.UUID) error
	// Called when the Manager creates the K8s Job for this task.
	MarkMapTaskRunning(ctx context.Context, arg MarkMapTaskRunningParams) error
	// Called when the worker POSTs to /tasks/:id/complete.
	// output_path is the MinIO object path of the part file.
	MarkReduceTaskCompleted(ctx context.Context, arg MarkReduceTaskCompletedParams) error
	MarkReduceTaskFailed(ctx context.Context, taskID uuid.UUID) error
	// Called when the Manager creates the K8s Job for this task.
	MarkReduceTaskRunning(ctx context.Context, arg MarkReduceTaskRunningParams) error
	UpdateJobStatus(ctx context.Context, arg UpdateJobStatusParams) error
}

var _ Querier = (*Queries)(nil)
