// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package db

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

type Querier interface {
	AddWorkflowDependency(ctx context.Context, arg AddWorkflowDependencyParams) error
	CancelJob(ctx context.Context, jobID uuid.UUID) error
	// Returns all parents of a stage and their status
	CheckStageDependencies(ctx context.Context, arg CheckStageDependenciesParams) ([]string, error)
	// Useful for an admin dashboard or metrics endpoint.
	CountJobsByStatus(ctx context.Context) ([]CountJobsByStatusRow, error)
	// Atomically read how many tasks are COMPLETED vs total.
	// Used by the Manager to decide when to advance to REDUCE_PHASE.
	CountMapTasksByStatus(ctx context.Context, jobID uuid.UUID) (CountMapTasksByStatusRow, error)
	// Used by the Manager to decide when the job is fully COMPLETED.
	CountReduceTasksByStatus(ctx context.Context, jobID uuid.UUID) (CountReduceTasksByStatusRow, error)
	CreateJob(ctx context.Context, arg CreateJobParams) (Job, error)
	CreateMapTask(ctx context.Context, arg CreateMapTaskParams) (MapTask, error)
	CreateReduceTask(ctx context.Context, arg CreateReduceTaskParams) (ReduceTask, error)
	CreateWorkflow(ctx context.Context, arg CreateWorkflowParams) (Workflow, error)
	DeleteCachedPlugin(ctx context.Context, sourceHash string) error
	DeleteJob(ctx context.Context, jobID uuid.UUID) error
	FailJob(ctx context.Context, arg FailJobParams) error
	// Used by the Manager on startup to re-attach to in-flight jobs it owns.
	GetActiveJobsByReplica(ctx context.Context, ownerReplica string) ([]Job, error)
	GetAllJobs(ctx context.Context) ([]Job, error)
	GetCachedPlugin(ctx context.Context, sourceHash string) (PluginCache, error)
	GetDownstreamStages(ctx context.Context, arg GetDownstreamStagesParams) ([]string, error)
	GetJob(ctx context.Context, jobID uuid.UUID) (Job, error)
	GetJobsByUser(ctx context.Context, ownerUserID string) ([]Job, error)
	GetMapTask(ctx context.Context, taskID uuid.UUID) (MapTask, error)
	GetMapTaskJobNames(ctx context.Context, jobID uuid.UUID) ([]sql.NullString, error)
	// Used by the Manager when building the reduce task inputs.
	// Returns all completed map tasks and their output_locations for a job.
	GetMapTaskOutputLocations(ctx context.Context, jobID uuid.UUID) ([]GetMapTaskOutputLocationsRow, error)
	GetMapTasksByJob(ctx context.Context, jobID uuid.UUID) ([]MapTask, error)
	GetMapTasksByJobAndStatus(ctx context.Context, arg GetMapTasksByJobAndStatusParams) ([]MapTask, error)
	// Used by the Manager to find tasks ready to dispatch as K8s Jobs.
	GetPendingMapTasks(ctx context.Context, arg GetPendingMapTasksParams) ([]MapTask, error)
	// Used by the Manager to find tasks ready to dispatch as K8s Jobs.
	GetPendingReduceTasks(ctx context.Context, arg GetPendingReduceTasksParams) ([]ReduceTask, error)
	GetReduceTask(ctx context.Context, taskID uuid.UUID) (ReduceTask, error)
	GetReduceTaskJobNames(ctx context.Context, jobID uuid.UUID) ([]sql.NullString, error)
	// Used to build the final job output listing.
	GetReduceTaskOutputPaths(ctx context.Context, jobID uuid.UUID) ([]GetReduceTaskOutputPathsRow, error)
	GetReduceTasksByJob(ctx context.Context, jobID uuid.UUID) ([]ReduceTask, error)
	GetReduceTasksByJobAndStatus(ctx context.Context, arg GetReduceTasksByJobAndStatusParams) ([]ReduceTask, error)
	// Used by the timeout watchdog: find RUNNING tasks older than N seconds.
	GetStaleRunningMapTasks(ctx context.Context, dollar_1 sql.NullString) ([]MapTask, error)
	// Used by the timeout watchdog.
	GetStaleRunningReduceTasks(ctx context.Context, dollar_1 sql.NullString) ([]ReduceTask, error)
	GetWorkflow(ctx context.Context, workflowID uuid.UUID) (Workflow, error)
	GetWorkflowStages(ctx context.Context, workflowID uuid.NullUUID) ([]Job, error)
	IncrementMapTaskRetry(ctx context.Context, taskID uuid.UUID) error
	IncrementReduceTaskRetry(ctx context.Context, taskID uuid.UUID) error
	ListStalePlugins(ctx context.Context, dollar_1 sql.NullString) ([]PluginCache, error)
	// Called when the worker POSTs to /tasks/:id/complete.
	// output_locations is a JSONB array: [{"reducer_index":0,"path":"..."}]
	MarkMapTaskCompleted(ctx context.Context, arg MarkMapTaskCompletedParams) error
	MarkMapTaskFailed(ctx context.Context, taskID uuid.UUID) error
	// Called when the Manager creates the K8s Job for this task.
	MarkMapTaskRunning(ctx context.Context, arg MarkMapTaskRunningParams) error
	// Called when the worker POSTs to /tasks/:id/complete.
	// output_path is the MinIO object path of the part file.
	MarkReduceTaskCompleted(ctx context.Context, arg MarkReduceTaskCompletedParams) error
	MarkReduceTaskFailed(ctx context.Context, taskID uuid.UUID) error
	// Called when the Manager creates the K8s Job for this task.
	MarkReduceTaskRunning(ctx context.Context, arg MarkReduceTaskRunningParams) error
	UpdateJobMapperPath(ctx context.Context, arg UpdateJobMapperPathParams) error
	UpdateJobReducerPath(ctx context.Context, arg UpdateJobReducerPathParams) error
	UpdateJobStatus(ctx context.Context, arg UpdateJobStatusParams) error
	UpdatePluginLastUsed(ctx context.Context, sourceHash string) error
	UpdateWorkflowStatus(ctx context.Context, arg UpdateWorkflowStatusParams) (Workflow, error)
	UpsertCachedPlugin(ctx context.Context, arg UpsertCachedPluginParams) error
}

var _ Querier = (*Queries)(nil)
