// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: reduce_tasks.sql

package db

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const countReduceTasksByStatus = `-- name: CountReduceTasksByStatus :one
SELECT
    COUNT(*) FILTER (WHERE status = 'COMPLETED') AS completed,
    COUNT(*) FILTER (WHERE status = 'FAILED')    AS failed,
    COUNT(*)                                      AS total
FROM reduce_tasks
WHERE job_id = $1
`

type CountReduceTasksByStatusRow struct {
	Completed int64 `json:"completed"`
	Failed    int64 `json:"failed"`
	Total     int64 `json:"total"`
}

// Used by the Manager to decide when the job is fully COMPLETED.
func (q *Queries) CountReduceTasksByStatus(ctx context.Context, jobID uuid.UUID) (CountReduceTasksByStatusRow, error) {
	row := q.queryRow(ctx, q.countReduceTasksByStatusStmt, countReduceTasksByStatus, jobID)
	var i CountReduceTasksByStatusRow
	err := row.Scan(&i.Completed, &i.Failed, &i.Total)
	return i, err
}

const createReduceTask = `-- name: CreateReduceTask :one
INSERT INTO reduce_tasks (
    job_id,
    task_index
) VALUES (
    $1, $2
)
RETURNING task_id, job_id, task_index, status, k8s_job_name, worker_pod, retry_count, started_at, completed_at, output_path
`

type CreateReduceTaskParams struct {
	JobID     uuid.UUID `json:"job_id"`
	TaskIndex int32     `json:"task_index"`
}

func (q *Queries) CreateReduceTask(ctx context.Context, arg CreateReduceTaskParams) (ReduceTask, error) {
	row := q.queryRow(ctx, q.createReduceTaskStmt, createReduceTask, arg.JobID, arg.TaskIndex)
	var i ReduceTask
	err := row.Scan(
		&i.TaskID,
		&i.JobID,
		&i.TaskIndex,
		&i.Status,
		&i.K8sJobName,
		&i.WorkerPod,
		&i.RetryCount,
		&i.StartedAt,
		&i.CompletedAt,
		&i.OutputPath,
	)
	return i, err
}

const getPendingReduceTasks = `-- name: GetPendingReduceTasks :many
SELECT task_id, job_id, task_index, status, k8s_job_name, worker_pod, retry_count, started_at, completed_at, output_path FROM reduce_tasks
WHERE job_id = $1
  AND status = 'PENDING'
ORDER BY task_index
LIMIT $2
`

type GetPendingReduceTasksParams struct {
	JobID uuid.UUID `json:"job_id"`
	Limit int32     `json:"limit"`
}

// Used by the Manager to find tasks ready to dispatch as K8s Jobs.
func (q *Queries) GetPendingReduceTasks(ctx context.Context, arg GetPendingReduceTasksParams) ([]ReduceTask, error) {
	rows, err := q.query(ctx, q.getPendingReduceTasksStmt, getPendingReduceTasks, arg.JobID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ReduceTask{}
	for rows.Next() {
		var i ReduceTask
		if err := rows.Scan(
			&i.TaskID,
			&i.JobID,
			&i.TaskIndex,
			&i.Status,
			&i.K8sJobName,
			&i.WorkerPod,
			&i.RetryCount,
			&i.StartedAt,
			&i.CompletedAt,
			&i.OutputPath,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getReduceTask = `-- name: GetReduceTask :one
SELECT task_id, job_id, task_index, status, k8s_job_name, worker_pod, retry_count, started_at, completed_at, output_path FROM reduce_tasks
WHERE task_id = $1
LIMIT 1
`

func (q *Queries) GetReduceTask(ctx context.Context, taskID uuid.UUID) (ReduceTask, error) {
	row := q.queryRow(ctx, q.getReduceTaskStmt, getReduceTask, taskID)
	var i ReduceTask
	err := row.Scan(
		&i.TaskID,
		&i.JobID,
		&i.TaskIndex,
		&i.Status,
		&i.K8sJobName,
		&i.WorkerPod,
		&i.RetryCount,
		&i.StartedAt,
		&i.CompletedAt,
		&i.OutputPath,
	)
	return i, err
}

const getReduceTaskOutputPaths = `-- name: GetReduceTaskOutputPaths :many
SELECT task_index, output_path
FROM reduce_tasks
WHERE job_id = $1
  AND status = 'COMPLETED'
ORDER BY task_index
`

type GetReduceTaskOutputPathsRow struct {
	TaskIndex  int32          `json:"task_index"`
	OutputPath sql.NullString `json:"output_path"`
}

// Used to build the final job output listing.
func (q *Queries) GetReduceTaskOutputPaths(ctx context.Context, jobID uuid.UUID) ([]GetReduceTaskOutputPathsRow, error) {
	rows, err := q.query(ctx, q.getReduceTaskOutputPathsStmt, getReduceTaskOutputPaths, jobID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetReduceTaskOutputPathsRow{}
	for rows.Next() {
		var i GetReduceTaskOutputPathsRow
		if err := rows.Scan(&i.TaskIndex, &i.OutputPath); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getReduceTasksByJob = `-- name: GetReduceTasksByJob :many
SELECT task_id, job_id, task_index, status, k8s_job_name, worker_pod, retry_count, started_at, completed_at, output_path FROM reduce_tasks
WHERE job_id = $1
ORDER BY task_index
`

func (q *Queries) GetReduceTasksByJob(ctx context.Context, jobID uuid.UUID) ([]ReduceTask, error) {
	rows, err := q.query(ctx, q.getReduceTasksByJobStmt, getReduceTasksByJob, jobID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ReduceTask{}
	for rows.Next() {
		var i ReduceTask
		if err := rows.Scan(
			&i.TaskID,
			&i.JobID,
			&i.TaskIndex,
			&i.Status,
			&i.K8sJobName,
			&i.WorkerPod,
			&i.RetryCount,
			&i.StartedAt,
			&i.CompletedAt,
			&i.OutputPath,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getReduceTasksByJobAndStatus = `-- name: GetReduceTasksByJobAndStatus :many
SELECT task_id, job_id, task_index, status, k8s_job_name, worker_pod, retry_count, started_at, completed_at, output_path FROM reduce_tasks
WHERE job_id = $1
  AND status = $2
ORDER BY task_index
`

type GetReduceTasksByJobAndStatusParams struct {
	JobID  uuid.UUID `json:"job_id"`
	Status string    `json:"status"`
}

func (q *Queries) GetReduceTasksByJobAndStatus(ctx context.Context, arg GetReduceTasksByJobAndStatusParams) ([]ReduceTask, error) {
	rows, err := q.query(ctx, q.getReduceTasksByJobAndStatusStmt, getReduceTasksByJobAndStatus, arg.JobID, arg.Status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ReduceTask{}
	for rows.Next() {
		var i ReduceTask
		if err := rows.Scan(
			&i.TaskID,
			&i.JobID,
			&i.TaskIndex,
			&i.Status,
			&i.K8sJobName,
			&i.WorkerPod,
			&i.RetryCount,
			&i.StartedAt,
			&i.CompletedAt,
			&i.OutputPath,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getStaleRunningReduceTasks = `-- name: GetStaleRunningReduceTasks :many
SELECT task_id, job_id, task_index, status, k8s_job_name, worker_pod, retry_count, started_at, completed_at, output_path FROM reduce_tasks
WHERE status = 'RUNNING'
  AND started_at < NOW() - ($1 || ' seconds')::INTERVAL
`

// Used by the timeout watchdog.
func (q *Queries) GetStaleRunningReduceTasks(ctx context.Context, dollar_1 sql.NullString) ([]ReduceTask, error) {
	rows, err := q.query(ctx, q.getStaleRunningReduceTasksStmt, getStaleRunningReduceTasks, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ReduceTask{}
	for rows.Next() {
		var i ReduceTask
		if err := rows.Scan(
			&i.TaskID,
			&i.JobID,
			&i.TaskIndex,
			&i.Status,
			&i.K8sJobName,
			&i.WorkerPod,
			&i.RetryCount,
			&i.StartedAt,
			&i.CompletedAt,
			&i.OutputPath,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const incrementReduceTaskRetry = `-- name: IncrementReduceTaskRetry :exec
UPDATE reduce_tasks
SET
    retry_count  = retry_count + 1,
    status       = 'PENDING',
    k8s_job_name = NULL,
    worker_pod   = NULL,
    started_at   = NULL
WHERE task_id = $1
`

func (q *Queries) IncrementReduceTaskRetry(ctx context.Context, taskID uuid.UUID) error {
	_, err := q.exec(ctx, q.incrementReduceTaskRetryStmt, incrementReduceTaskRetry, taskID)
	return err
}

const markReduceTaskCompleted = `-- name: MarkReduceTaskCompleted :exec
UPDATE reduce_tasks
SET
    status       = 'COMPLETED',
    output_path  = $2,
    completed_at = NOW()
WHERE task_id = $1
`

type MarkReduceTaskCompletedParams struct {
	TaskID     uuid.UUID      `json:"task_id"`
	OutputPath sql.NullString `json:"output_path"`
}

// Called when the worker POSTs to /tasks/:id/complete.
// output_path is the MinIO object path of the part file.
func (q *Queries) MarkReduceTaskCompleted(ctx context.Context, arg MarkReduceTaskCompletedParams) error {
	_, err := q.exec(ctx, q.markReduceTaskCompletedStmt, markReduceTaskCompleted, arg.TaskID, arg.OutputPath)
	return err
}

const markReduceTaskFailed = `-- name: MarkReduceTaskFailed :exec
UPDATE reduce_tasks
SET
    status       = 'FAILED',
    completed_at = NOW()
WHERE task_id = $1
`

func (q *Queries) MarkReduceTaskFailed(ctx context.Context, taskID uuid.UUID) error {
	_, err := q.exec(ctx, q.markReduceTaskFailedStmt, markReduceTaskFailed, taskID)
	return err
}

const markReduceTaskRunning = `-- name: MarkReduceTaskRunning :exec
UPDATE reduce_tasks
SET
    status       = 'RUNNING',
    k8s_job_name = $2,
    started_at   = NOW()
WHERE task_id = $1
`

type MarkReduceTaskRunningParams struct {
	TaskID     uuid.UUID      `json:"task_id"`
	K8sJobName sql.NullString `json:"k8s_job_name"`
}

// Called when the Manager creates the K8s Job for this task.
func (q *Queries) MarkReduceTaskRunning(ctx context.Context, arg MarkReduceTaskRunningParams) error {
	_, err := q.exec(ctx, q.markReduceTaskRunningStmt, markReduceTaskRunning, arg.TaskID, arg.K8sJobName)
	return err
}
